# Cypher 查询模板
"""
预定义的 Cypher 查询模板，用于常见的图谱操作
"""

from .templates import (
    # 竞争分析
    COMPETITION_COLLAPSE_QUERY,
    FIND_AFFECTED_COMBOS_QUERY,
    
    # 空白点挖掘
    OPPORTUNITY_DISCOVERY_QUERY,
    HIGH_UNMET_NEED_QUERY,
    
    # 数据诚信
    DATA_INTEGRITY_CHECK_QUERY,
    SUSPICIOUS_DATA_QUERY,
    
    # 通用查询
    DRUG_FULL_PROFILE_QUERY,
    INDICATION_LANDSCAPE_QUERY,
    COMPANY_PIPELINE_QUERY,
)

__all__ = [
    "COMPETITION_COLLAPSE_QUERY",
    "FIND_AFFECTED_COMBOS_QUERY",
    "OPPORTUNITY_DISCOVERY_QUERY",
    "HIGH_UNMET_NEED_QUERY",
    "DATA_INTEGRITY_CHECK_QUERY",
    "SUSPICIOUS_DATA_QUERY",
    "DRUG_FULL_PROFILE_QUERY",
    "INDICATION_LANDSCAPE_QUERY",
    "COMPANY_PIPELINE_QUERY",
]

